language: java
sudo: true
jdk:
  - openjdk15
script: ./gradlew build --scan -s
before_install: chmod +x gradlew
jobs:
  include:
    - stage: test
      script: ./gradlew clean test
#deploy:
#  provider: heroku
#  api_key: $heroku_api_key
#  app: testSpringBoot
#  on:
#    dev