language: java
sudo: true
jdk:
  - openjdk15
script: ./gradlew build --scan -s
before_install: chmod +x gradlew
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5433
    - PGUSER=travis
before_script:
  - psql --version
  - psql -c 'create database student;' -U travis
  - psql -f './sql/test.sql -d student;' -U travis
jobs:
  include:
    - stage: test
      script: ./gradlew test
#deploy:
#  provider: heroku
#  api_key: $heroku_api_key
#  app: testSpringBoot
#  on:
#    dev